package communication.dto;

public enum InquiryManagerActions {
    ALL_INQUIRY,
    ADD_INQUIRY,
    TEST,
    CANCEL_INQUIRY,
    GET_INQUIRY_STATUS,
    GET_NUMBER_OF_INQUIRIES_ON_MONTH,
    REPRESENTATIVE_ENTRY,
    REPRESENTATIVE_EXIT,
    ADD_REPRESENTATIVE,
    MANAGER_LOGIN
}
